imagePullSecrets:
  - name: acr-secret

frontend:
  image:
    repository: shopflowacr.azurecr.io/shopflow-frontend
    tag: 81cc12d5b484266e4dced120a4cd9ac7d64445b8
  replicas: 1
  port: 3000

backend:
  image:
    repository: shopflowacr.azurecr.io/shopflow-backend
    tag: 81cc12d5b484266e4dced120a4cd9ac7d64445b8
  replicas: 1
  port: 5000

mongodb:
  image: mongo:6
  replicas: 1
  port: 27017
  storage: 1Gi

secret:
  mongoUri: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L3Nob3BmbG93P2F1dGhTb3VyY2U9YWRtaW4=
